services:
  app:
    image: suistwn/foodorder-api:latest
    container_name: api-foodorder
    ports:
      - "8084:8080"
    restart: unless-stopped
    networks:
      - apps-network

networks:
  apps-network:
    name: apps-network
