services:
  app:
    build: .
    image: suistwn/foodorder-api:latest
    container_name: api-foodorder
    ports:
      - "8084:8080"
    restart: unless-stopped
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    name: financial-tracker-network
