# Data source
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRED_IN}

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Warna di konsol
spring.output.ansi.enabled=always

# Set ke WARN agar tidak banyak log "sampah" saat startup
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN

# JPA & HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF

# Package utama Anda tetap INFO agar log buatan Anda muncul
logging.level.com.dibimbing.medicareflow==INFO

# Format log konsol (berwarna & 1 baris)
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5p) %clr(%logger{20}){cyan} %clr(:){faint} %m [%clr(%ex{short}){white}]%n

# Proxy Handling
server.forward-headers-strategy=native